version: '3.9'

services:

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    expose:
      - "9000"
    depends_on:
      - mysql
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html

  mysql:
    build: ./requirements/mariadb
    expose:
      - "3306"
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql

networks:
  inception_network:
    driver: bridge

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: volumes
      device: /home/gasna/data/wordpress
      o: bind

  db-data:
    driver: local
    driver_opts:
      type: volumes
      device: /home/gasna/data/mysql
      o: bind
